exception: add MaxSAT exception
To be able to replace the exit(_ERROR_) sequence, a proper replacement is
required. To be able to print the file and line information, use a
stringstream, so that string and int can be combined easily.