exception: throw and catch
Instead of stopping with exit(_ERROR_), throw an exception to be able to
leave the program at a single place. This also simplifies debugging and
testing for memory safety and similar properties.